<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Inventory\Korp.Invoice.Inventory.Domain\Korp.Invoice.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Korp.Invoice.Shared\Korp.Invoice.Shared.csproj" />
    <ProjectReference Include="..\Korp.Invoice.Billing.Domain\Korp.Invoice.Billing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
